name: CD Pipeline (Auto Deploy)

on:
  push:
    tags:
      - 'v*.*'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, linux]

    steps:
      - name: Завантаження коду з репозиторію
        uses: actions/checkout@v4

      - name: Передача файлів на Target Node
        run: |
          ssh -o StrictHostKeyChecking=no student@192.168.50.20 "mkdir -p ~/app-deploy"
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" --exclude='.git' --exclude='actions-runner' ./ student@192.168.50.20:~/app-deploy/

      - name: Збірка образу та розгортання через Docker
        run: |
          ssh -o StrictHostKeyChecking=no student@192.168.50.20 << 'EOF'
          cd ~/app-deploy
          
          # 1. Зупиняємо та видаляємо старий контейнер
          sudo docker stop task-tracker-container || true
          sudo docker rm task-tracker-container || true
          
          # 2. Збираємо образ
          sudo docker build -t task-tracker-image .
          
          # 3. Запускаємо контейнер (порт 8000 для відповідності верифікації)
          sudo docker run -d -p 8000:5000 --name task-tracker-container task-tracker-image
          
          # 4. Налаштування Nginx
          sudo apt-get update && sudo apt-get install nginx -y
          sudo cp task-tracker.conf /etc/nginx/sites-available/task-tracker
          sudo ln -sf /etc/nginx/sites-available/task-tracker /etc/nginx/sites-enabled/
          sudo rm -f /etc/nginx/sites-enabled/default
          sudo systemctl restart nginx
          EOF

      - name: Верифікація розгортання проекту
        run: |
          echo "Запуск процесу верифікації сервісу через Nginx..."
          STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" http://192.168.50.20:9999/)
          echo "Отримано HTTP статус-код: $STATUS_CODE"
          if [ "$STATUS_CODE" -eq 200 ]; then
            echo "УСПІХ: Сервіс доступний, Nginx налаштований коректно (Код 200)!"
            exit 0
          else
            echo "ПОМИЛКА: Сервіс повернув код $STATUS_CODE або недоступний!"
            exit 1
          fi